### ISSUE TITLE
取消下载对话框选项问题

### ISSUE THREAD

**Issue by UrakawaMinori** [powhu/Shinsi2#1]
<img width="273" alt="tim 20181113164046" src="https://user-images.githubusercontent.com/30543568/48400991-e6cff600-e762-11e8-87ae-2da518c7c611.png">
第一反應Cancel和Ok是一個意思，No和Yes好一些吧。

**Comment by powhu** [comment]
👍 太習慣取消鍵title用cancel了
已修改
