### ISSUE TITLE
报错啦~[!] Unable to find a specification for `AloeStackView`

### ISSUE THREAD

**Issue by examango** [powhu/Shinsi2#2]
pod install的时候 =- =
[!] Unable to find a specification for `AloeStackView`

**Comment by powhu** [comment]
你的cocoapods版本太舊吧
改用cocoapods的官方App看看吧
https://cocoapods.org/app

**Comment by examango** [comment]
#

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by examango** [comment]
>你的cocoapods版本太舊吧 ...

@powhu 1.5.3，的确比较旧了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
