### ISSUE TITLE
你觉得，图像不清晰，是什么问题? 谢谢

### ISSUE THREAD

**Issue by chinanf-boy** [powhu/Shinsi2#4]
就是很蒙，难道我要🦐啦

再点个👍

**Comment by powhu** [comment]
哪邊的圖像不清晰？確定不是網路的問題？

**Comment by chinanf-boy** [comment]
就是进到，单页的时候，图片的清晰度很低，(就像标清画质似的)

**Comment by chinanf-boy** [comment]
如下:

<img src="https://user-images.githubusercontent.com/20272484/50537981-ca690b00-0ba2-11e9-8fbb-5717c088f70f.jpg" height="500px">

**Comment by powhu** [comment]
如果有打開Hath Perks的Multi-Page Viewer要關掉
如果還是不行在App中的Setting打開My Settings
在網頁中瀏覽試試看，如果網頁中也開不出來應該就是網頁問題
如果不是去網頁版的設定中把所有設定都改回預設試試看
